language: node_js
node_js:
  - "10.12.0"

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

services:
  - mongodb

install: yarn install:all

before_script:
  - yarn build

script:
  - yarn lint
  - yarn test
  - yarn e2e:ci
